### PR TITLE
Feature/add-editor-config

### PR DESCRIPTION
**Pull request by Dangkeys**

### CODE REVIEW

**Review by Dangkeys — COMMENTED** [review]
Proof of work krub: https://jam.dev/c/18d84ba7-3770-43c1-bf2a-d400b71b796f

**Comment by billza555** [comment]
Video don't have anything to see

**Review by billza555 — CHANGES_REQUESTED** [review]
I want video to see proqress

**Review by Dangkeys — COMMENTED** [review]
proof of work 2: https://jam.dev/c/bc191b6c-fa27-40a4-a0d2-e23a81634e08

**Pull request merged**
